// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjOYNsdceMNbUS3n2oBU7VSeII01cOh2s',
    appId: '1:756020390968:web:2fe7f778588cb491ef0acd',
    messagingSenderId: '756020390968',
    projectId: 'handphone10-a87df',
    authDomain: 'handphone10-a87df.firebaseapp.com',
    storageBucket: 'handphone10-a87df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsv0m_X_notpmO-SldzjsqWg74lh63ZcM',
    appId: '1:756020390968:android:f0218c3599de1138ef0acd',
    messagingSenderId: '756020390968',
    projectId: 'handphone10-a87df',
    storageBucket: 'handphone10-a87df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcuALNo7tGPXO0eKg23kXMS6VYPHCaw_s',
    appId: '1:756020390968:ios:1cf036e7659083e7ef0acd',
    messagingSenderId: '756020390968',
    projectId: 'handphone10-a87df',
    storageBucket: 'handphone10-a87df.appspot.com',
    androidClientId: '756020390968-4lhakmp2lt36aojep8im76ragpa078h5.apps.googleusercontent.com',
    iosClientId: '756020390968-ukkb72n437tus33ag87clb5otunurt9b.apps.googleusercontent.com',
    iosBundleId: 'com.smartphonereview.smartphoneReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcuALNo7tGPXO0eKg23kXMS6VYPHCaw_s',
    appId: '1:756020390968:ios:1cf036e7659083e7ef0acd',
    messagingSenderId: '756020390968',
    projectId: 'handphone10-a87df',
    storageBucket: 'handphone10-a87df.appspot.com',
    androidClientId: '756020390968-4lhakmp2lt36aojep8im76ragpa078h5.apps.googleusercontent.com',
    iosClientId: '756020390968-ukkb72n437tus33ag87clb5otunurt9b.apps.googleusercontent.com',
    iosBundleId: 'com.smartphonereview.smartphoneReview',
  );
}
